import fs from 'fs/promises';
import path from 'path';
import type { EnrichedData } from '../ai/types.js';
import type { GenerateOptions } from '../config/types.js';
import { scaffoldTemplate } from './scaffold.js';
import { writePortfolioData } from './data-writer.js';
import { logger } from '../utils/logger.js';

export class SiteGenerator {
  async generate(
    data: EnrichedData,
    opts: GenerateOptions,
  ): Promise<void> {
    const outputDir = path.resolve(process.cwd(), opts.output);

    logger.step(`Scaffolding site → ${outputDir}`);
    await scaffoldTemplate(outputDir);

    logger.step('Writing portfolio data & rendering HTML...');
    await writePortfolioData(data, outputDir, opts);

    logger.step('Writing README...');
    await this.writeReadme(data, outputDir);
  }

  private async writeReadme(data: EnrichedData, outputDir: string): Promise<void> {
    const name = data.viewer.name ?? data.viewer.login;
    const content = `# ${name}'s Portfolio

Generated by [git-folio](https://github.com/zedotech/git-folio) on ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}.

This is a plain static site — no build step needed. Open \`index.html\` in your browser to view the portfolio.

## Preview locally

Use the git-folio Web UI (Preview tab) to serve this folder on \`http://localhost:4321\`, or use any static file server:

\`\`\`bash
npx serve .
\`\`\`

## Refresh data

Run the following from the **git-folio project root** to pull the latest GitHub data and regenerate:

\`\`\`bash
node dist/index.js generate --output <path-to-this-folder>
\`\`\`

## Deploy

This folder can be deployed directly to any static hosting service:

- **Vercel**: run \`npx vercel\` in this directory
- **Netlify**: drag and drop this folder to app.netlify.com
- **GitHub Pages**: push the contents to your \`gh-pages\` branch
`;
    await fs.writeFile(path.join(outputDir, 'README.md'), content, 'utf-8');
  }
}
