import fs from 'fs/promises';
import path from 'path';
import { execSync } from 'child_process';
import type { EnrichedData } from '../ai/types.js';
import type { GenerateOptions } from '../config/types.js';
import { scaffoldTemplate } from './scaffold.js';
import { writePortfolioData } from './data-writer.js';
import { logger } from '../utils/logger.js';

export class SiteGenerator {
  async generate(
    data: EnrichedData,
    opts: GenerateOptions,
  ): Promise<void> {
    const outputDir = path.resolve(process.cwd(), opts.output);

    logger.step(`Scaffolding Astro site → ${outputDir}`);
    await scaffoldTemplate(outputDir);

    logger.step('Writing portfolio data...');
    await writePortfolioData(data, outputDir, opts);

    logger.step('Writing README...');
    await this.writeReadme(data, outputDir);

    logger.step('Installing dependencies...');
    execSync('npm install', { cwd: outputDir, stdio: 'inherit' });
  }

  private async writeReadme(data: EnrichedData, outputDir: string): Promise<void> {
    const name = data.viewer.name ?? data.viewer.login;
    const content = `# ${name}'s Portfolio

Generated by [git-folio](https://github.com/zedotech/git-folio) on ${new Date().toLocaleDateString('en-US', { dateStyle: 'long' })}.

## Preview locally

Start the development server to preview the site in your browser:

\`\`\`bash
npm run dev
\`\`\`

Open http://localhost:4321. The page reloads automatically when you edit \`src/data/portfolio.json\`.

## Build for production

When you're happy with the result, generate the static site:

\`\`\`bash
npm run build
\`\`\`

This creates \`dist/\` — a folder of plain HTML/CSS/JS ready to deploy anywhere.

> **Important**: Do not open the HTML files in \`dist/\` directly in your browser — the assets use absolute paths that only work when served through a web server. Use \`npm run preview\` to check the build locally, or deploy to a hosting service.

To preview the build before deploying:

\`\`\`bash
npm run preview
\`\`\`

## Hide or show repos

Open \`src/data/portfolio.json\` and set \`"enable": false\` on any repo you want to hide:

\`\`\`json
{ "name": "old-project", "enable": false, ... }
\`\`\`

Save the file. In dev mode the page updates instantly; for production re-run \`npm run build\`.

## Refresh data

Run the following from the **git-folio project root** (not this directory) to pull the latest GitHub data and regenerate:

\`\`\`bash
node dist/index.js generate --output <path-to-this-folder>
\`\`\`

Your \`enable\` settings are preserved across regenerations.

## Deploy

After \`npm run build\`, deploy the \`dist/\` folder:

- **Vercel**: run \`npx vercel\` in this directory
- **Netlify**: drag and drop \`dist/\` to app.netlify.com
- **GitHub Pages**: push the contents of \`dist/\` to your \`gh-pages\` branch
`;
    await fs.writeFile(path.join(outputDir, 'README.md'), content, 'utf-8');
  }
}
